AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Express API on Lambda via @vendia/serverless-express

Globals:
  Function:
    Timeout: 30

Resources:
  ExpressApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/index.handler
      Runtime: nodejs20.x
      CodeUri: .
      MemorySize: 512
      Environment:
        Variables:
          NODE_ENV: production
          MONGODB_URI: !Ref MongoDbUri
          S3_BUCKET_NAME: !Ref S3BucketName
          CLOUDFRONT_DOMAIN: !Ref CloudFrontDomain
          RAZORPAY_KEY_ID: !Ref RazorpayKeyId
          RAZORPAY_KEY_SECRET: !Ref RazorpayKeySecret
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Parameters:
  MongoDbUri:
    Type: String
    Description: MongoDB connection string
  S3BucketName:
    Type: String
    Description: S3 bucket name
  CloudFrontDomain:
    Type: String
    Description: CloudFront domain
  RazorpayKeyId:
    Type: String
    Description: Razorpay Key Id
  RazorpayKeySecret:
    Type: String
    Description: Razorpay Key Secret
